# Generated by Django 3.2.8 on 2022-10-03 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artworks', '0001_initial'),
        ('category', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('machine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtWorkPref',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colors', models.ManyToManyField(blank=True, to='artworks.Color')),
                ('matters', models.ManyToManyField(blank=True, to='artworks.Matter')),
                ('mediums', models.ManyToManyField(blank=True, to='artworks.Medium')),
            ],
            options={
                'db_table': 'pref_art',
            },
        ),
        migrations.CreateModel(
            name='CatPref',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('machine.menucategoryuser',),
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art_works', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prefered.artworkpref')),
                ('peoples', models.ManyToManyField(blank=True, to='category.People')),
                ('periods', models.ManyToManyField(blank=True, to='category.Period')),
                ('places', models.ManyToManyField(blank=True, to='category.Place')),
                ('professions', models.ManyToManyField(blank=True, to='category.Profession')),
                ('styles', models.ManyToManyField(blank=True, to='category.Style')),
                ('things', models.ManyToManyField(blank=True, to='category.Thing')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prefers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pref_user',
            },
        ),
    ]
