# Generated by Django 3.2.8 on 2022-10-03 05:50

import buildx.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title Album')),
            ],
        ),
        migrations.CreateModel(
            name='AlbumCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Category Album')),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=30, verbose_name='Banner Title')),
            ],
        ),
        migrations.CreateModel(
            name='ImageBuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('image', buildx.models.ImageFieldChecker(upload_to='images', validators=[buildx.models.validate_image_extension])),
            ],
            options={
                'db_table': 'image_build',
            },
        ),
        migrations.CreateModel(
            name='Shield',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=30, verbose_name='Shield Title')),
                ('image', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='buildx.imagebuild')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Object Name')),
                ('slug', models.SlugField(blank=True, max_length=150, null=True)),
                ('is_approuve', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='buildx.objectname')),
            ],
            options={
                'db_table': 'build_obj_name',
            },
        ),
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=25, verbose_name='Title')),
                ('artist_name', models.CharField(blank=True, max_length=25, verbose_name='Artist name')),
                ('video_link', models.URLField(blank=True, max_length=50, verbose_name='video name')),
                ('image_link', models.URLField(blank=True, max_length=50, verbose_name='Image Link')),
                ('live_link', models.URLField(blank=True, max_length=50, verbose_name='Live Link')),
                ('homepage_link', models.URLField(blank=True, max_length=50, verbose_name='Homepage Link')),
                ('vitea_link', models.URLField(blank=True, max_length=50, verbose_name='Vitea Link')),
                ('domus_link', models.URLField(blank=True, max_length=50, verbose_name='Domus Link')),
                ('albums', models.ManyToManyField(blank=True, to='buildx.Album')),
                ('banner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buildx.banner')),
                ('image', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buildx.imagebuild')),
                ('object_name', models.ManyToManyField(blank=True, to='buildx.ObjectName')),
                ('shield', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buildx.shield')),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='build', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='banner',
            name='image',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='buildx.imagebuild'),
        ),
        migrations.AddField(
            model_name='album',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='buildx.albumcategory'),
        ),
        migrations.AddField(
            model_name='album',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buildx.imagebuild'),
        ),
        migrations.AddConstraint(
            model_name='objectname',
            constraint=models.UniqueConstraint(fields=('parent', 'name'), name='unic_parent_and_child'),
        ),
    ]
