# Generated by Django 3.2.8 on 2022-10-03 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('slug', models.SlugField(blank=True, max_length=150, null=True)),
                ('counter', models.PositiveIntegerField(default=0)),
                ('is_allow', models.BooleanField(default=False)),
                ('period', models.CharField(blank=True, max_length=30)),
                ('user_name', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('slug', models.SlugField(blank=True, max_length=150, null=True)),
                ('counter', models.PositiveIntegerField(default=0)),
                ('is_allow', models.BooleanField(default=False)),
                ('period', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('slug', models.SlugField(blank=True, max_length=150, null=True)),
                ('counter', models.PositiveIntegerField(default=0)),
                ('is_allow', models.BooleanField(default=False)),
                ('period', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('slug', models.SlugField(blank=True, max_length=150, null=True)),
                ('counter', models.PositiveIntegerField(default=0)),
                ('is_allow', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('slug', models.SlugField(blank=True, max_length=150, null=True)),
                ('counter', models.PositiveIntegerField(default=0)),
                ('is_allow', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('slug', models.SlugField(blank=True, max_length=150, null=True)),
                ('counter', models.PositiveIntegerField(default=0)),
                ('is_allow', models.BooleanField(default=False)),
                ('period', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('slug', models.SlugField(blank=True, max_length=150, null=True)),
                ('counter', models.PositiveIntegerField(default=0)),
                ('is_allow', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, max_length=200)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='category.category')),
                ('peoples', models.ManyToManyField(blank=True, to='category.People')),
                ('periods', models.ManyToManyField(blank=True, to='category.Period')),
                ('places', models.ManyToManyField(blank=True, to='category.Place')),
                ('things', models.ManyToManyField(blank=True, to='category.Thing')),
            ],
            options={
                'db_table': 'category',
                'unique_together': {('name', 'slug', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='MainCategory',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('category.category',),
        ),
    ]
