# Generated by Django 3.2.8 on 2023-03-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20221003_0549'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
